apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: postgres:5432
    user: username
    secureJsonData:
      password: 'password'
    jsonData:
      database: database
      sslmode: 'disable'
      maxOpenConns: 100 
      maxIdleConns: 100 
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 903
      timescaledb: false