{
 "title": "Main",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    c.username,\n    c.id AS conversation_id,\n    c.question,\n    c.answer,\n    c.response_time,\n    c.token_usage,\n    c.search_results,\n    c.timestamp AS conversation_timestamp,\n    f.feedback,\n    f.timestamp AS feedback_timestamp\nFROM\n    conversations c\nJOIN\n    feedback f\nON\n    c.id = f.conversation_id\nWHERE\n    f.feedback IN (+1, -1);\n"
    }
   ]
  },
  {
   "title": "Avg Token Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select avg(token_usage) from conversations; "
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select avg(response_time) from conversations;"
    }
   ]
  },
  {
   "title": "Feedback summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 8 },
   "targets": [
    {
     "rawSql": "select feedback as Type, count(feedback) as Count\nfrom feedback GROUP BY feedback"
    }
   ]
  }
 ]
}